spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lgpd
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8082